export const categoryStyles = {
  Product: 'bg-blue-50 text-blue-600',
  Design: 'bg-violet-50 text-violet-600',
  Marketing: 'bg-amber-50 text-amber-600',
  Engineering: 'bg-teal-50 text-teal-600',
  'Customer Success': 'bg-emerald-50 text-emerald-600',
  Finance: 'bg-rose-50 text-rose-600',
  Sales: 'bg-orange-50 text-orange-600',
  Leadership: 'bg-indigo-50 text-indigo-600',
  People: 'bg-pink-50 text-pink-600',
  General: 'bg-slate-100 text-slate-600',
}

export const meetings = [
  {
    id: 'product-strategy-sync',
    title: 'Product Strategy Sync',
    category: 'Product',
    date: '2026-07-28',
    durationMinutes: 45,
    actionItems: 6,
    keyDecisions: 3,
    participants: 5,
    attendees: ['AL', 'JM', 'SK'],
    status: 'Analyzed',
  },
  {
    id: 'design-critique',
    title: 'Design Critique',
    category: 'Design',
    date: '2026-07-27',
    durationMinutes: 40,
    actionItems: 5,
    keyDecisions: 2,
    participants: 4,
    attendees: ['RM', 'TL'],
    status: 'Analyzed',
  },
  {
    id: 'weekly-marketing-review',
    title: 'Weekly Marketing Review',
    category: 'Marketing',
    date: '2026-07-24',
    durationMinutes: 30,
    actionItems: 4,
    keyDecisions: 2,
    participants: 4,
    attendees: ['CB', 'NP'],
    status: 'Analyzed',
  },
  {
    id: 'sprint-planning',
    title: 'Sprint Planning',
    category: 'Engineering',
    date: '2026-07-22',
    durationMinutes: 70,
    actionItems: 9,
    keyDecisions: 4,
    participants: 7,
    attendees: ['DK', 'MG', 'PS'],
    status: 'Analyzed',
  },
  {
    id: 'customer-success-check-in',
    title: 'Customer Success Check-in',
    category: 'Customer Success',
    date: '2026-07-21',
    durationMinutes: 25,
    actionItems: 3,
    keyDecisions: 1,
    participants: 3,
    attendees: ['EW', 'HT'],
    status: 'Analyzed',
  },
  {
    id: 'q3-budget-review',
    title: 'Q3 Budget Review',
    category: 'Finance',
    date: '2026-07-18',
    durationMinutes: 50,
    actionItems: 7,
    keyDecisions: 5,
    participants: 5,
    attendees: ['JB', 'LR'],
    status: 'Analyzed',
  },
  {
    id: 'engineering-retro',
    title: 'Engineering Retro',
    category: 'Engineering',
    date: '2026-07-15',
    durationMinutes: 20,
    actionItems: 2,
    keyDecisions: 1,
    participants: 6,
    attendees: ['MG', 'DK'],
    status: 'Analyzed',
  },
  {
    id: 'sales-pipeline-review',
    title: 'Sales Pipeline Review',
    category: 'Sales',
    date: '2026-07-11',
    durationMinutes: 35,
    actionItems: 6,
    keyDecisions: 3,
    participants: 4,
    attendees: ['OT', 'FS'],
    status: 'Analyzed',
  },
  {
    id: 'leadership-offsite-recap',
    title: 'Leadership Offsite Recap',
    category: 'Leadership',
    date: '2026-07-08',
    durationMinutes: 90,
    actionItems: 11,
    keyDecisions: 6,
    participants: 8,
    attendees: ['ZB', 'KH', 'WP'],
    status: 'Analyzed',
  },
  {
    id: 'onboarding-process-review',
    title: 'Onboarding Process Review',
    category: 'People',
    date: '2026-07-04',
    durationMinutes: 30,
    actionItems: 4,
    keyDecisions: 2,
    participants: 3,
    attendees: ['YN', 'QC'],
    status: 'Analyzed',
  },
]
