export const categoryStyles = {
  Product: 'bg-tag-blue-bg text-tag-blue-text',
  Design: 'bg-tag-violet-bg text-tag-violet-text',
  Marketing: 'bg-tag-amber-bg text-tag-amber-text',
  Engineering: 'bg-tag-teal-bg text-tag-teal-text',
  'Customer Success': 'bg-tag-emerald-bg text-tag-emerald-text',
  Finance: 'bg-tag-rose-bg text-tag-rose-text',
  Sales: 'bg-tag-orange-bg text-tag-orange-text',
  Leadership: 'bg-tag-indigo-bg text-tag-indigo-text',
  People: 'bg-tag-pink-bg text-tag-pink-text',
  General: 'bg-tag-neutral-bg text-tag-neutral-text',
}

export const sentimentTones = {
  Positive: 'bg-success-subtle-bg text-success-subtle-text',
  Neutral: 'bg-tag-neutral-bg text-tag-neutral-text',
  Mixed: 'bg-warning-subtle-bg text-warning-subtle-text',
}

export const meetings = [
  {
    id: 'product-strategy-sync',
    title: 'Product Strategy Sync',
    category: 'Product',
    date: '2026-07-28',
    durationMinutes: 45,
    actionItems: 6,
    keyDecisions: 3,
    participants: 5,
    attendees: ['AL', 'JM', 'SK'],
    status: 'Analyzed',
  },
  {
    id: 'design-critique',
    title: 'Design Critique',
    category: 'Design',
    date: '2026-07-27',
    durationMinutes: 40,
    actionItems: 5,
    keyDecisions: 2,
    participants: 4,
    attendees: ['RM', 'TL'],
    status: 'Analyzed',
  },
  {
    id: 'weekly-marketing-review',
    title: 'Weekly Marketing Review',
    category: 'Marketing',
    date: '2026-07-24',
    durationMinutes: 30,
    actionItems: 4,
    keyDecisions: 2,
    participants: 4,
    attendees: ['CB', 'NP'],
    status: 'Analyzed',
  },
  {
    id: 'sprint-planning',
    title: 'Sprint Planning',
    category: 'Engineering',
    date: '2026-07-22',
    durationMinutes: 70,
    actionItems: 9,
    keyDecisions: 4,
    participants: 7,
    attendees: ['DK', 'MG', 'PS'],
    status: 'Analyzed',
  },
  {
    id: 'customer-success-check-in',
    title: 'Customer Success Check-in',
    category: 'Customer Success',
    date: '2026-07-21',
    durationMinutes: 25,
    actionItems: 3,
    keyDecisions: 1,
    participants: 3,
    attendees: ['EW', 'HT'],
    status: 'Analyzed',
  },
  {
    id: 'q3-budget-review',
    title: 'Q3 Budget Review',
    category: 'Finance',
    date: '2026-07-18',
    durationMinutes: 50,
    actionItems: 7,
    keyDecisions: 5,
    participants: 5,
    attendees: ['JB', 'LR'],
    status: 'Analyzed',
  },
  {
    id: 'engineering-retro',
    title: 'Engineering Retro',
    category: 'Engineering',
    date: '2026-07-15',
    durationMinutes: 20,
    actionItems: 2,
    keyDecisions: 1,
    participants: 6,
    attendees: ['MG', 'DK'],
    status: 'Analyzed',
  },
  {
    id: 'sales-pipeline-review',
    title: 'Sales Pipeline Review',
    category: 'Sales',
    date: '2026-07-11',
    durationMinutes: 35,
    actionItems: 6,
    keyDecisions: 3,
    participants: 4,
    attendees: ['OT', 'FS'],
    status: 'Analyzed',
  },
  {
    id: 'leadership-offsite-recap',
    title: 'Leadership Offsite Recap',
    category: 'Leadership',
    date: '2026-07-08',
    durationMinutes: 90,
    actionItems: 11,
    keyDecisions: 6,
    participants: 8,
    attendees: ['ZB', 'KH', 'WP'],
    status: 'Analyzed',
  },
  {
    id: 'onboarding-process-review',
    title: 'Onboarding Process Review',
    category: 'People',
    date: '2026-07-04',
    durationMinutes: 30,
    actionItems: 4,
    keyDecisions: 2,
    participants: 3,
    attendees: ['YN', 'QC'],
    status: 'Analyzed',
  },
]
